main: me.nicole.majoritysleeping.MajoritySleeping
name: MajoritySleep
version: 0.3
author: CyNicole
description: Checks to ensure a majority of players are sleeping before executing a sleep.
commands:
    afk:
        description: Set yourself afk
        usage: /afk